import mod.client.extraClientApi as clientApi
clientApi.HideAirSupplyGUI(True)
clientApi.HideArmorGui(True)
clientApi.HideChangePersonGui(True)
clientApi.HideChatGUI(True)
clientApi.HideCrossHairGUI(True)
clientApi.HideEmoteGUI(True)
clientApi.HideExpGui(True)
clientApi.HideFoldGUI(True)
clientApi.HideHealthGui(True)
clientApi.HideHorseHealthGui(True)
clientApi.HideHudGUI(True)
clientApi.HideHungerGui(True)
clientApi.HideInteractGui(True)
clientApi.HideJumpGui(True)
clientApi.HideMoveGui(True)
clientApi.HideNeteaseStoreGui(True)
clientApi.HidePauseGUI(True)
clientApi.HideReportGUI(True)
clientApi.HideSlotBarGui(True)
clientApi.HideSneakGui(True)
clientApi.HideSwimGui(True)
clientApi.HideVoiceGUI(True)
clientApi.HideWalkGui(True)
LVID = clientApi.GetLevelId()
comp = clientApi.GetEngineCompFactory().CreateGame(LVID)
res = comp.SetEmoteSwitch(False)
CF = clientApi.GetEngineCompFactory()
Msg = CF.CreateTextNotifyClient(LVID).SetLeftCornerNotify