import mod.client.extraClientApi as clientApi
comp = clientApi.GetEngineCompFactory().CreateParticleSystem(None)
localId = clientApi.GetLocalPlayerId()

parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 1, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0.9, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0.8, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0.7, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0.6, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0.5, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0.4, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0.3, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0.2, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0.1, 0.9), (0, 0, 0))
parId = comp.Create("netease:tutorial_particle")
comp.BindEntity(parId, localId, "body", (0, 0, 0.9), (0, 0, 0))