import mod.client.extraClientApi as clientApi
clientApi.HideAirSupplyGUI(False)
clientApi.HideArmorGui(False)
clientApi.HideChangePersonGui(False)
clientApi.HideChatGUI(False)
clientApi.HideCrossHairGUI(False)
clientApi.HideEmoteGUI(False)
clientApi.HideExpGui(False)
clientApi.HideFoldGUI(False)
clientApi.HideHealthGui(False)
clientApi.HideHorseHealthGui(False)
clientApi.HideHudGUI(False)
clientApi.HideHungerGui(False)
clientApi.HideInteractGui(False)
clientApi.HideJumpGui(False)
clientApi.HideMoveGui(False)
clientApi.HideNeteaseStoreGui(False)
clientApi.HidePauseGUI(False)
clientApi.HideReportGUI(False)
clientApi.HideSlotBarGui(False)
clientApi.HideSneakGui(False)
clientApi.HideSwimGui(False)
clientApi.HideVoiceGUI(False)
clientApi.HideWalkGui(False)
LVID = clientApi.GetLevelId()
comp = clientApi.GetEngineCompFactory().CreateGame(LVID)
res = comp.SetEmoteSwitch(False)
CF = clientApi.GetEngineCompFactory()
Msg = CF.CreateTextNotifyClient(LVID).SetLeftCornerNotify